### PR TITLE
Refactor: Cleaned up Icon to remove Link, useNav to have external link alt text and updated PR Template

### PR DESCRIPTION
**Pull request by chadstewart**
## Description

1. Updated Icon to no longer have a Link component in it. Made no sense to have it there.
2. Updated useNav to take external link alt text and the main-nav component to use it.
3. Updated PR Template to have guide on how to add issue number so the issue closes when the PR is merged.

## Related Issue

Resolves: #70 
Resolves: #68
Resolves: #65

## Motivation and Context

Above issues explain the motivation behind this PR.

## How Has This Been Tested?

n/a

## Screenshots (if appropriate):

n/a

### CODE REVIEW

**Comment by chadstewart** [comment]
Hey @TAKANOME-DEV, @dev-phantom, @royanger, could you take a look at this and let me know please?

**Review by royanger — APPROVED** [review]
Looks good.

**Comment by dev-phantom** [comment]
Looks good

please merge the PR so i can fetch upstream before making my next commit

**Review by TAKANOME-DEV — APPROVED** [review]
LGTM :+1:

**Pull request merged**
