### PR TITLE
Added Code Quality GitHub Action

### LINKED ISSUE #51: Add ESLint GitHub Action
## Developer Experience Issue

**Please describe your Developer Experience Issue.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

So there's linting rules for the project that can cause errors that causes the build to break when adding PRs. This was an issue in PR issue #50.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Thinking of adding a GitHub Action to run linting on the project when code is pushed. I'm not sure if this is the best solution but it's the thing that came to mind first. I'll look into other solutions.

**Describe alternatives you've considered**

We could have pre-commit hooks that'll run linting before pushing the code. Or we could make the linting rules warnings instead of errors so builds won't break on linting rules.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

### PR DESCRIPTION
**Pull request by chadstewart**
## Description

Added a GitHub action that runs tests and linter whenever code is pushed to dev or main.

## Related Issue

Fixes #51

## Motivation and Context

Had a recent problem in #50 where was getting a lint error when making a PR. Instead of having devs have to run the linter every time they pushed, wanted to do linting when the code was pushed.

## How Has This Been Tested?

When code is pushed to this PR, the GitHub Action is run. All the actions need to pass to be able to merge this code.

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by chadstewart** [comment]
Hey @TAKANOME-DEV, I think I got the GitHub actions working but I'm not sure. Mind taking a look?

**Comment by chadstewart** [comment]
frodo-baggins-its-over

**Review by TAKANOME-DEV — APPROVED** [review]
LGTM :+1: 
After merging this pr, we will see if the cypress tests will pass :sweat_smile:

**Comment by chadstewart** [comment]
> LGTM +1 After merging this pr, we will see if the cypress tests will pass sweat_smile

They pass already. Was wrestling with them a bit trying to get this to work. The GitHub Action will work but if the tests don't pass then the PR will be sad.

**Comment by TAKANOME-DEV** [comment]
> They pass already. Was wrestling with them a bit trying to get this to work.
>
Nice job :+1: :rocket: 
> The GitHub Action will work but if the tests don't pass then the PR will be sad.
>
Yeah, definitely :sweat_smile:

**Pull request merged**
