### PR TITLE
feat: add tests infrastructure

### LINKED ISSUE #29: Add Vitest, React Testing Library and Cypress
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

There is currently no automated tests for the project.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

We should add Vitest, React Testing Library and Cypress to the project.

**Describe alternatives you've considered**

Haven't considered any alternatives at this time.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

n/a

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
## Description

This PR:
- adds cypress for e2e tests
- adds vitest for unit/integration tests
- adds test for `lib/utils/capitalize.ts` utility
- fixes a typo in the contributing file
## Related Issue

Fixes #29 
## Screenshots (if appropriate):

### CODE REVIEW

**Comment by chadstewart** [comment]
Okay, so this is new! I'll have to fix that.

Actually @TAKANOME-DEV, do you havw recommendations on how to accept contributions? Should be a way to avoid this error in the future but still leaving the responsibility for reviewing the PR to the maintainer.

Yikes man, I'm so new to managing an open source project! 🤣

**Comment by chadstewart** [comment]
Oh thanks by the way for all of this initial work! Really appreciate it a bunch!

**Comment by TAKANOME-DEV** [comment]
> Actually @TAKANOME-DEV, do you havw recommendations on how to accept contributions? Should be a way to avoid this error in the future but still leaving the responsibility for reviewing the PR to the maintainer.
> 
It seems like you have deployment protection enabled. I think only people on the team can view the deploy previews. If you want the deploy preview to be available on all prs, you may need to change your configs. Learn more -> https://vercel.com/docs/concepts/deployments/deployment-protection

> Yikes man, I'm so new to managing an open source project! :rofl:
>
It's tough :sweat_smile:, I don't have that much experience in managing open source, but I did start one which is on standby (needs design)

**Comment by chadstewart** [comment]
Hey @TAKANOME-DEV, looks like they're some ESLint rules that are causing errors. Do you mind fixing that please? Deploy's failing because of it.

**Comment by chadstewart** [comment]
> > Hey @TAKANOME-DEV, looks like they're some ESLint rules that are causing errors. Do you mind fixing that please? Deploy's failing because of it.
> 
> Sure, I didn't ran eslint sweat_smile (time to configure github action for that maybe)

Yeah, I'm probably gonna make an issue and look into that in a bit, lol. I'm getting better at this!

**Comment by chadstewart** [comment]
@TAKANOME-DEV So I'm getting this error now:

Type error: 'homepage.cy.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

Any idea what this is?

**Comment by TAKANOME-DEV** [comment]
> Type error: 'homepage.cy.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
> 
Since `isolateModules` is set to `true` in the `tsconfig` file, all implementation files must be modules (which means it has some form of import/export).
The [cypress docs](https://docs.cypress.io/guides/tooling/typescript-support) recommend to add another tsconfig file for the tests with different configs

**Comment by TAKANOME-DEV** [comment]
Oh sorry, I thought it was a lint error and it turns out that it was a build error. Should be good now :smile:

**Comment by chadstewart** [comment]
> Oh sorry, I thought it was a lint error and it turns out that it was a build error. Should be good now smile

Nah, it's cool. That did it!

I'll merge it in! This was definitely a fun PR! Definitely looking forward to digging into Cypress and Vitest some more!

**Comment by chadstewart** [comment]
By the way, thanks so much for the contribution @TAKANOME-DEV and thanks for being the first ever outside contribution to this project!

**Comment by TAKANOME-DEV** [comment]
> By the way, thanks so much for the contribution @TAKANOME-DEV and thanks for being the first ever outside contribution to this project!
>
Looking forward to contributing more to the project :rocket:

**Comment by chadstewart** [comment]
> > By the way, thanks so much for the contribution @TAKANOME-DEV and thanks for being the first ever outside contribution to this project!
> 
> Looking forward to contributing more to the project 🚀

Yeah man! Feel free to look through the remaining open issues and let me know if you want yo take on anything else!

**Pull request merged**
